# Generated by Django 4.2.2 on 2023-09-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vegetable_alter_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vegetable',
        ),
    ]
