# Generated by Django 4.2.2 on 2023-09-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vegetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Vegetable',
        ),
    ]
