# Generated by Django 4.2.2 on 2023-09-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_delete_product_delete_vegetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('vg', 'Vegetables'), ('ft', 'Fruits')], max_length=100)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
