# Generated by Django 4.2.2 on 2023-09-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
