# Generated by Django 4.2.2 on 2023-09-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
