# Generated by Django 4.2.2 on 2023-09-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_customer_user_delete_userregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
