# Generated by Django 4.2.2 on 2023-09-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
