# Generated by Django 4.2.2 on 2023-09-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
